name: Docker
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  ENVIRONMENT: production
  IMAGE_NAME: notangles
  AWS_REGION: ap-southeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com

jobs:
  build-client:
    name: 'Build (Client)'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActions-ECR-ECS-DeployRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: client
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
          platforms: linux/amd64
          file: client/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
            GOOGLE_ANALYTICS_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
            SENTRY_INGEST_CLIENT=${{ secrets.SENTRY_INGEST_CLIENT }}
            SENTRY_TRACE_RATE_CLIENT=${{ secrets.SENTRY_TRACE_RATE_CLIENT }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}-client:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}-client:latest

  build:
    name: 'Build (${{ matrix.component }})'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: [server, auto_server]
        include:
          - component: server
            name: backend
          - component: auto_server
            name: auto-timetabler-server
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActions-ECR-ECS-DeployRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.component }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
          platforms: linux/amd64
          file: ${{ matrix.component }}/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/task-definition/TestContainer:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/task-definition/TestContainer:latest

  deploy:
    name: Deploy (ECS)
    runs-on: ubuntu-latest
    needs: [build-client, build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
    concurrency: production
    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: eklavya-joshi/deployment
          token: ${{ secrets.GH_TOKEN }}
          ref: dev

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActions-ECR-ECS-DeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Download client task definition
        id: client-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/${{ env.ENVIRONMENT }}/client-task-definition.json # Path to your client task definition JSON
          container-name: notangles # Name of the client container in your task definition
          image: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-client:${{ github.sha }}

      # - name: Download backend task definition
      #   id: backend-task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: .aws/${{ env.ENVIRONMENT }}/backend-task-definition.json # Path to your backend task definition JSON
      #     container-name: notangles-backend # Name of the backend container in your task definition
      #     image: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}

      # - name: Download auto-timetabler task definition
      #   id: auto-timetabler-task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: .aws/${{ env.ENVIRONMENT }}/auto-timetabler-task-definition.json # Path to your auto-timetabler task definition JSON
      #     container-name: notangles-auto-timetabler-server # Name of the auto-timetabler container
      #     image: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}-auto-timetabler-server:${{ github.sha }}

      - name: Deploy client to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.client-task-def.outputs.task-definition }}
          service: notangles-client-service-${{ env.ENVIRONMENT }} # Your ECS client service name
          cluster: notangles-cluster-${{ env.ENVIRONMENT }} # Your ECS cluster name
          wait-for-service-stability: true

      # - name: Deploy backend to ECS service
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.backend-task-def.outputs.task-definition }}
      #     service: notangles-backend-service-${{ env.ENVIRONMENT }} # Your ECS backend service name
      #     cluster: notangles-cluster-${{ env.ENVIRONMENT }} # Your ECS cluster name
      #     wait-for-service-stability: true

      # - name: Deploy auto-timetabler to ECS service
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.auto-timetabler-task-def.outputs.task-definition }}
      #     service: notangles-auto-timetabler-service-${{ env.ENVIRONMENT }} # Your ECS auto-timetabler service name
      #     cluster: notangles-cluster-${{ env.ENVIRONMENT }} # Your ECS cluster name
      #     wait-for-service-stability: true